"""Turn hand-written tutor arcs into full traces, with the REAL student replying.

    python src/replay_good_traces.py --out runs/good_traces.jsonl

Every trace we have comes from one mediocre policy, so preference pairs drawn
from it are mid-vs-mid, which is mostly annotator noise. This adds a genuinely
good tier for the pairs to compare against.

The tutor turns are written by hand (data/good_tutor_turns.json); the student
turns are generated by the same frozen Qwen2.5-0.5B used in training, and the
outcome is scored through the same `choose()` channel and the same leak rule.
If the student turns were also hand-written, a reward model could separate the
tiers on the student's voice instead of on the tutor's quality - which is the one
thing it must not learn.

Runs on a laptop: 0.5B on MPS or CPU, no network.

The tutor arcs are non-adaptive: they were written before seeing the student's
replies, so they diagnose the problem rather than the person. That is a real
limitation of this tier and is recorded in the trace as `adaptive: false`.
"""

from __future__ import annotations

import argparse
import json

import paths
import rewards

OPENERS = [
    "I'm stuck on this one.",
    "I don't really get what it's asking.",
    "hmm i'm not sure where to start",
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arcs", default=str(paths.DATA / "good_tutor_turns.json"))
    ap.add_argument("--picks", default="/tmp/pick50.json")
    ap.add_argument("--student", default="Qwen/Qwen2.5-0.5B-Instruct")
    ap.add_argument("--device", default=None)
    ap.add_argument("--out", default="runs/good_traces.jsonl")
    args = ap.parse_args()

    arcs = json.load(open(args.arcs))["arcs"]
    picks = json.load(open(args.picks))

    import torch
    from zpd_filter import HFStudent
    device = args.device or ("mps" if torch.backends.mps.is_available()
                             else "cuda" if torch.cuda.is_available() else "cpu")
    print(f"student: {args.student} on {device}")
    student = HFStudent(args.student, device=device)

    n = 0
    with open(args.out, "w") as f:
        for idx_str, turns in sorted(arcs.items(), key=lambda kv: int(kv[0])):
            it = picks[int(idx_str)]
            q, choices, gi = it["question"], it["choices"], it["gold_idx"]
            gold = choices[gi]
            distractors = [c for j, c in enumerate(choices) if j != gi]

            lines = [f"Student: {OPENERS[int(idx_str) % len(OPENERS)]}"]
            for msg in turns:
                lines.append(f"Tutor: {msg}")
                reply = student.reply(["\n".join(lines)], max_new_tokens=48)[0]
                lines.append(f"Student: {reply.strip()}")

            transcript = "\n".join(lines)
            tutor_text = "\n".join(turns)
            picked = student.choose(q, choices, hint=transcript)
            solved = float(picked == gi)
            leaked = rewards.leaked_answer(tutor_text, gold, distractors, question=q)
            f.write(json.dumps({
                "step": -1,
                "tier": "good",
                "adaptive": False,
                "prompt": q,
                "completion": transcript,
                "choices": choices,
                "gold_idx": gi,
                "gold": gold,
                "solved": solved,
                "leaked": leaked,
                "turns": len(turns),
                "reward": -1.0 if leaked else solved,
                "student_answer": choices[picked],
                "subject": it.get("subject"),
                "grade": it.get("grade"),
            }) + "\n")
            n += 1
            if n % 10 == 0:
                print(f"  {n}/{len(arcs)}")

    rows = [json.loads(l) for l in open(args.out)]
    print(f"\nwrote {n} good traces -> {args.out}")
    print(f"solved {sum(r['solved'] for r in rows) / n:.3f}   "
          f"leaked {sum(r['leaked'] for r in rows) / n:.3f}")
    print("(v2's own policy, for comparison: solved 0.304, leaked 0.385)")


if __name__ == "__main__":
    main()
